# Generated by Django 5.1.3 on 2025-02-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='case_number',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
