# Generated by Django 4.2.4 on 2025-09-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_receipe_address_receipe_family_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='abortions',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='allopathic_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='appetite',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='aversions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='basis_of_prescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='bowel_habits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='bp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='built',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='cardiovascular_system',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='chosen_remedy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='cravings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='cycle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='dreams',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='flow',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='full_term_deliveries',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='gastrointestinal_system',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='genitourinary_system',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='gravida',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='habits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='locomotor_system',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='menarche_age',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='menopause',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='mental_generals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='miasmatic_diagnosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='nervous_system',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='obstetric_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='pallor_cyanosis_edema',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='para',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='perspiration',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='potency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='pulse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='repertorization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='repetition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='respiration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='respiratory_system',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='sexual_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='sleep',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='temperature',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='thermal_reaction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='thirst',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='tongue_nails_skin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='totality_of_symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='urine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipe',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
