# Generated by Django 4.2.4 on 2025-09-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_receipe_abortions_receipe_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='receipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipe'),
        ),
    ]
